databases:
  - name: expenseai-db
    databaseName: expenseai
    user: expenseai
    plan: free

services:
  - type: web
    name: expense-ai-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: expenseai-db
          property: connectionString
